### PR TITLE
Added learningGit.html file

### PR DESCRIPTION
**Pull request by vvyas23**
Have created a learningGit.html file just for learning git pull request.

### CODE REVIEW

**Comment by vaibhavdev** [comment]
So you also added a second commit to it and updated the file

**Comment by vaibhavdev** [comment]
Hi it seems you have added a 3rd commit which contains the learningGit2.txt file. We do not need that file, you can remove it from the request

**Comment by vvyas23** [comment]
Ok will remove the learningGit2.txt file from the branch

**Comment by vaibhavdev** [comment]
ok good, thankyou for removing the learningGit2.txt file from the pull request

**Pull request merged**
